image: python:3.11

tasks:
  - name: Setup Airflow + Postgres
    init: |
      export AIRFLOW_HOME=~/airflow
      pip install -r requirements.txt
      # Start Postgres in background
      sudo apt-get update && sudo apt-get install -y postgresql postgresql-contrib
      sudo service postgresql start
      sudo -u postgres psql -c "CREATE USER airflow WITH PASSWORD 'airflow';"
      sudo -u postgres createdb airflow_db -O airflow
      airflow db init
      airflow users create \
        --username admin \
        --firstname Gitpod \
        --lastname User \
        --role Admin \
        --email admin@example.com \
        --password admin
    command: |
      airflow webserver --port 8080

ports:
  - port: 8080
    onOpen: open-preview
